sonar.projectKey=Trampoline999_mernspace-c-auth-service
sonar.organization=trampoline999

sonar.projectName=mernspace-c-auth-service

sonar.sources=src

sonar.tests=tests

sonar.exclusions=**/node_modules/**/* , **/dist/**/* , **/migration/**/*

sonar.qualitgate.wait = true